spring.application.name=demo
# For AWS
spring.datasource.url=jdbc:postgresql://localhost:5432/football
spring.datasource.username=footballuser
spring.datasource.password=football

# For local
#spring.datasource.url=jdbc:postgresql://localhost:5433/footballAssignment
#spring.datasource.username=postgres
#spring.datasource.password=football


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

